export const FETCH_GOODS_START = 'FETCH_GOODS_START';
export const FETCH_GOODS_SUCCES = 'FETCH_GOODS_SUCCES';
export const FETCH_GOODS_FAILURE = 'FETCH_GOODS_FAILURE';

export const FETCH_PRODUCT_BY_ID_START = 'FETCH_PRODUCT_BY_ID_START';
export const FETCH_PRODUCT_BY_ID_SUCCESS = 'FETCH_PRODUCT_BY_ID_SUCCESS';
export const FETCH_PRODUCT_BY_ID_FAILURE = 'FETCH_PRODUCT_BY_ID_FAILURE';

export const ADD_PRODUCT_TO_BASKET = 'ADD_PRODUCT_TO_BASKET';

export const DELETE_PRODUCT_FROM_BASKET = 'DELETE_PRODUCT_FROM_BASKET';

export const CLEAN_BASKET = 'CLEAN_BASKET';

export const SORT_GOODS = 'SORT_GOODS';