export const FETCH_GOODS_START = 'FETCH_GOODS_START';
export const FETCH_GOODS_SUCCES = 'FETCH_GOODS_SUCCES';
export const FETCH_GOODS_FAILURE = 'FETCH_GOODS_FAILURE';

export const SORT_DESCEND_START = 'SORT_DESCEND_START';
export const SORT_DESCEND_SUCCESS = 'SORT_DESCEND_SUCCESS';
export const SORT_DESCEND_FAILURE = 'SORT_DESCEND_FAILURE';

export const FETCH_PRODUCT_BY_ID_START = 'FETCH_PRODUCT_BY_ID_START';
export const FETCH_PRODUCT_BY_ID_SUCCESS = 'FETCH_PRODUCT_BY_ID_SUCCESS';
export const FETCH_PRODUCT_BY_ID_FAILURE = 'FETCH_PRODUCT_BY_ID_FAILURE';

export const ADD_PRODUCT_TO_BASCKET = 'ADD_PRODUCT_TO_BASCKET';